# Config file for automatic testing at travis-ci.com

matrix:
  include:
    - name: "Python 3.6.5 on macOS 10.13.6 (xcode 9.4)"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -r requirements.txt
      install: pip3 install -e .
      script:
        - pytest --cov=./
        - flake8 mtoolnote
    - name: "Python 3.7.5 on macOS 10.14.4 (xcode 10.2)"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -r requirements.txt
      install: pip3 install -e .
      script:
        - pytest --cov=./
        - flake8 mtoolnote
    - name: "Python 3.6.7 on Ubuntu 16.04"
      os: linux
      language: python
      python: 3.6
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -r requirements.txt
      install: pip3 install -e .
      script:
        - pytest --cov=./
        - flake8 mtoolnote
    - name: "Python 3.7.1 on Ubuntu 16.04"
      os: linux
      language: python
      python: 3.7
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -r requirements.txt
      install: pip3 install -e .
      script:
        - pytest --cov=./
        - flake8 mtoolnote
after_success:
  - codecov
